// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.0
// 	protoc        v5.26.1
// source: blogs_service.proto

package blogs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Blog_BlogStatus int32

const (
	Blog_Draft     Blog_BlogStatus = 0
	Blog_Published Blog_BlogStatus = 1
	Blog_Closed    Blog_BlogStatus = 2
	Blog_Active    Blog_BlogStatus = 3
	Blog_Famous    Blog_BlogStatus = 4
)

// Enum value maps for Blog_BlogStatus.
var (
	Blog_BlogStatus_name = map[int32]string{
		0: "Draft",
		1: "Published",
		2: "Closed",
		3: "Active",
		4: "Famous",
	}
	Blog_BlogStatus_value = map[string]int32{
		"Draft":     0,
		"Published": 1,
		"Closed":    2,
		"Active":    3,
		"Famous":    4,
	}
)

func (x Blog_BlogStatus) Enum() *Blog_BlogStatus {
	p := new(Blog_BlogStatus)
	*p = x
	return p
}

func (x Blog_BlogStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Blog_BlogStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_blogs_service_proto_enumTypes[0].Descriptor()
}

func (Blog_BlogStatus) Type() protoreflect.EnumType {
	return &file_blogs_service_proto_enumTypes[0]
}

func (x Blog_BlogStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Blog_BlogStatus.Descriptor instead.
func (Blog_BlogStatus) EnumDescriptor() ([]byte, []int) {
	return file_blogs_service_proto_rawDescGZIP(), []int{0, 0}
}

type BlogVote_VoteType int32

const (
	BlogVote_Downvote BlogVote_VoteType = 0
	BlogVote_Upvote   BlogVote_VoteType = 1
)

// Enum value maps for BlogVote_VoteType.
var (
	BlogVote_VoteType_name = map[int32]string{
		0: "Downvote",
		1: "Upvote",
	}
	BlogVote_VoteType_value = map[string]int32{
		"Downvote": 0,
		"Upvote":   1,
	}
)

func (x BlogVote_VoteType) Enum() *BlogVote_VoteType {
	p := new(BlogVote_VoteType)
	*p = x
	return p
}

func (x BlogVote_VoteType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlogVote_VoteType) Descriptor() protoreflect.EnumDescriptor {
	return file_blogs_service_proto_enumTypes[1].Descriptor()
}

func (BlogVote_VoteType) Type() protoreflect.EnumType {
	return &file_blogs_service_proto_enumTypes[1]
}

func (x BlogVote_VoteType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlogVote_VoteType.Descriptor instead.
func (BlogVote_VoteType) EnumDescriptor() ([]byte, []int) {
	return file_blogs_service_proto_rawDescGZIP(), []int{3, 0}
}

type Blog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID              int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Status          Blog_BlogStatus        `protobuf:"varint,4,opt,name=Status,proto3,enum=Blog_BlogStatus" json:"Status,omitempty"`
	AuthorId        int32                  `protobuf:"varint,5,opt,name=AuthorId,proto3" json:"AuthorId,omitempty"`
	Comments        []*BlogComment         `protobuf:"bytes,6,rep,name=Comments,proto3" json:"Comments,omitempty"`
	Votes           []*BlogVote            `protobuf:"bytes,7,rep,name=Votes,proto3" json:"Votes,omitempty"`
	Recommendations []*BlogsRecommendation `protobuf:"bytes,8,rep,name=Recommendations,proto3" json:"Recommendations,omitempty"`
}

func (x *Blog) Reset() {
	*x = Blog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blogs_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Blog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blog) ProtoMessage() {}

func (x *Blog) ProtoReflect() protoreflect.Message {
	mi := &file_blogs_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blog.ProtoReflect.Descriptor instead.
func (*Blog) Descriptor() ([]byte, []int) {
	return file_blogs_service_proto_rawDescGZIP(), []int{0}
}

func (x *Blog) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Blog) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Blog) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Blog) GetStatus() Blog_BlogStatus {
	if x != nil {
		return x.Status
	}
	return Blog_Draft
}

func (x *Blog) GetAuthorId() int32 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *Blog) GetComments() []*BlogComment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *Blog) GetVotes() []*BlogVote {
	if x != nil {
		return x.Votes
	}
	return nil
}

func (x *Blog) GetRecommendations() []*BlogsRecommendation {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

type BlogsRecommendation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID                       int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	BlogId                   int32 `protobuf:"varint,2,opt,name=BlogId,proto3" json:"BlogId,omitempty"`
	RecommenderId            int32 `protobuf:"varint,3,opt,name=RecommenderId,proto3" json:"RecommenderId,omitempty"`
	RecommendationReceiverId int32 `protobuf:"varint,4,opt,name=RecommendationReceiverId,proto3" json:"RecommendationReceiverId,omitempty"`
	Blog                     *Blog `protobuf:"bytes,5,opt,name=blog,proto3" json:"blog,omitempty"`
}

func (x *BlogsRecommendation) Reset() {
	*x = BlogsRecommendation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blogs_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogsRecommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogsRecommendation) ProtoMessage() {}

func (x *BlogsRecommendation) ProtoReflect() protoreflect.Message {
	mi := &file_blogs_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogsRecommendation.ProtoReflect.Descriptor instead.
func (*BlogsRecommendation) Descriptor() ([]byte, []int) {
	return file_blogs_service_proto_rawDescGZIP(), []int{1}
}

func (x *BlogsRecommendation) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *BlogsRecommendation) GetBlogId() int32 {
	if x != nil {
		return x.BlogId
	}
	return 0
}

func (x *BlogsRecommendation) GetRecommenderId() int32 {
	if x != nil {
		return x.RecommenderId
	}
	return 0
}

func (x *BlogsRecommendation) GetRecommendationReceiverId() int32 {
	if x != nil {
		return x.RecommendationReceiverId
	}
	return 0
}

func (x *BlogsRecommendation) GetBlog() *Blog {
	if x != nil {
		return x.Blog
	}
	return nil
}

type BlogComment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	AuthorId  int32                  `protobuf:"varint,2,opt,name=AuthorId,proto3" json:"AuthorId,omitempty"`
	BlogId    int32                  `protobuf:"varint,3,opt,name=BlogId,proto3" json:"BlogId,omitempty"`
	Text      string                 `protobuf:"bytes,4,opt,name=Text,proto3" json:"Text,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
}

func (x *BlogComment) Reset() {
	*x = BlogComment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blogs_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogComment) ProtoMessage() {}

func (x *BlogComment) ProtoReflect() protoreflect.Message {
	mi := &file_blogs_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogComment.ProtoReflect.Descriptor instead.
func (*BlogComment) Descriptor() ([]byte, []int) {
	return file_blogs_service_proto_rawDescGZIP(), []int{2}
}

func (x *BlogComment) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *BlogComment) GetAuthorId() int32 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *BlogComment) GetBlogId() int32 {
	if x != nil {
		return x.BlogId
	}
	return 0
}

func (x *BlogComment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *BlogComment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BlogComment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type BlogVote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     int32             `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserId int32             `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	BlogId int32             `protobuf:"varint,3,opt,name=BlogId,proto3" json:"BlogId,omitempty"`
	Type   BlogVote_VoteType `protobuf:"varint,4,opt,name=Type,proto3,enum=BlogVote_VoteType" json:"Type,omitempty"`
}

func (x *BlogVote) Reset() {
	*x = BlogVote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blogs_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogVote) ProtoMessage() {}

func (x *BlogVote) ProtoReflect() protoreflect.Message {
	mi := &file_blogs_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogVote.ProtoReflect.Descriptor instead.
func (*BlogVote) Descriptor() ([]byte, []int) {
	return file_blogs_service_proto_rawDescGZIP(), []int{3}
}

func (x *BlogVote) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *BlogVote) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BlogVote) GetBlogId() int32 {
	if x != nil {
		return x.BlogId
	}
	return 0
}

func (x *BlogVote) GetType() BlogVote_VoteType {
	if x != nil {
		return x.Type
	}
	return BlogVote_Downvote
}

type CreateBlogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blog *Blog `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
}

func (x *CreateBlogRequest) Reset() {
	*x = CreateBlogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blogs_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlogRequest) ProtoMessage() {}

func (x *CreateBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blogs_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlogRequest.ProtoReflect.Descriptor instead.
func (*CreateBlogRequest) Descriptor() ([]byte, []int) {
	return file_blogs_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateBlogRequest) GetBlog() *Blog {
	if x != nil {
		return x.Blog
	}
	return nil
}

type CreateBlogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateBlogResponse) Reset() {
	*x = CreateBlogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blogs_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlogResponse) ProtoMessage() {}

func (x *CreateBlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blogs_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlogResponse.ProtoReflect.Descriptor instead.
func (*CreateBlogResponse) Descriptor() ([]byte, []int) {
	return file_blogs_service_proto_rawDescGZIP(), []int{5}
}

type GetBlogByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetBlogByIdRequest) Reset() {
	*x = GetBlogByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blogs_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlogByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogByIdRequest) ProtoMessage() {}

func (x *GetBlogByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blogs_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogByIdRequest.ProtoReflect.Descriptor instead.
func (*GetBlogByIdRequest) Descriptor() ([]byte, []int) {
	return file_blogs_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetBlogByIdRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetBlogByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blog *Blog `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
}

func (x *GetBlogByIdResponse) Reset() {
	*x = GetBlogByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blogs_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlogByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogByIdResponse) ProtoMessage() {}

func (x *GetBlogByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blogs_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogByIdResponse.ProtoReflect.Descriptor instead.
func (*GetBlogByIdResponse) Descriptor() ([]byte, []int) {
	return file_blogs_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetBlogByIdResponse) GetBlog() *Blog {
	if x != nil {
		return x.Blog
	}
	return nil
}

type GetAllBlogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllBlogsRequest) Reset() {
	*x = GetAllBlogsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blogs_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllBlogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBlogsRequest) ProtoMessage() {}

func (x *GetAllBlogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blogs_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBlogsRequest.ProtoReflect.Descriptor instead.
func (*GetAllBlogsRequest) Descriptor() ([]byte, []int) {
	return file_blogs_service_proto_rawDescGZIP(), []int{8}
}

type GetAllBlogsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blogs []*Blog `protobuf:"bytes,1,rep,name=blogs,proto3" json:"blogs,omitempty"`
}

func (x *GetAllBlogsResponse) Reset() {
	*x = GetAllBlogsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blogs_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllBlogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBlogsResponse) ProtoMessage() {}

func (x *GetAllBlogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blogs_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBlogsResponse.ProtoReflect.Descriptor instead.
func (*GetAllBlogsResponse) Descriptor() ([]byte, []int) {
	return file_blogs_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllBlogsResponse) GetBlogs() []*Blog {
	if x != nil {
		return x.Blogs
	}
	return nil
}

type GetBlogsByAuthorsIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthorId string `protobuf:"bytes,1,opt,name=AuthorId,proto3" json:"AuthorId,omitempty"`
}

func (x *GetBlogsByAuthorsIdRequest) Reset() {
	*x = GetBlogsByAuthorsIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blogs_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlogsByAuthorsIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogsByAuthorsIdRequest) ProtoMessage() {}

func (x *GetBlogsByAuthorsIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blogs_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogsByAuthorsIdRequest.ProtoReflect.Descriptor instead.
func (*GetBlogsByAuthorsIdRequest) Descriptor() ([]byte, []int) {
	return file_blogs_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetBlogsByAuthorsIdRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type GetBlogsByAuthorsIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blogs []*Blog `protobuf:"bytes,1,rep,name=blogs,proto3" json:"blogs,omitempty"`
}

func (x *GetBlogsByAuthorsIdResponse) Reset() {
	*x = GetBlogsByAuthorsIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blogs_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlogsByAuthorsIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogsByAuthorsIdResponse) ProtoMessage() {}

func (x *GetBlogsByAuthorsIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blogs_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogsByAuthorsIdResponse.ProtoReflect.Descriptor instead.
func (*GetBlogsByAuthorsIdResponse) Descriptor() ([]byte, []int) {
	return file_blogs_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetBlogsByAuthorsIdResponse) GetBlogs() []*Blog {
	if x != nil {
		return x.Blogs
	}
	return nil
}

type GetBlogsByAuthorsIdsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthorsIds string `protobuf:"bytes,1,opt,name=AuthorsIds,proto3" json:"AuthorsIds,omitempty"`
}

func (x *GetBlogsByAuthorsIdsRequest) Reset() {
	*x = GetBlogsByAuthorsIdsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blogs_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlogsByAuthorsIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogsByAuthorsIdsRequest) ProtoMessage() {}

func (x *GetBlogsByAuthorsIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blogs_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogsByAuthorsIdsRequest.ProtoReflect.Descriptor instead.
func (*GetBlogsByAuthorsIdsRequest) Descriptor() ([]byte, []int) {
	return file_blogs_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetBlogsByAuthorsIdsRequest) GetAuthorsIds() string {
	if x != nil {
		return x.AuthorsIds
	}
	return ""
}

type GetBlogsByAuthorsIdsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blogs []*Blog `protobuf:"bytes,1,rep,name=blogs,proto3" json:"blogs,omitempty"`
}

func (x *GetBlogsByAuthorsIdsResponse) Reset() {
	*x = GetBlogsByAuthorsIdsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blogs_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlogsByAuthorsIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogsByAuthorsIdsResponse) ProtoMessage() {}

func (x *GetBlogsByAuthorsIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blogs_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogsByAuthorsIdsResponse.ProtoReflect.Descriptor instead.
func (*GetBlogsByAuthorsIdsResponse) Descriptor() ([]byte, []int) {
	return file_blogs_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetBlogsByAuthorsIdsResponse) GetBlogs() []*Blog {
	if x != nil {
		return x.Blogs
	}
	return nil
}

type SearchBlogByNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
}

func (x *SearchBlogByNameRequest) Reset() {
	*x = SearchBlogByNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blogs_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchBlogByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBlogByNameRequest) ProtoMessage() {}

func (x *SearchBlogByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blogs_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBlogByNameRequest.ProtoReflect.Descriptor instead.
func (*SearchBlogByNameRequest) Descriptor() ([]byte, []int) {
	return file_blogs_service_proto_rawDescGZIP(), []int{14}
}

func (x *SearchBlogByNameRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type SearchBlogByNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blogs []*Blog `protobuf:"bytes,1,rep,name=blogs,proto3" json:"blogs,omitempty"`
}

func (x *SearchBlogByNameResponse) Reset() {
	*x = SearchBlogByNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blogs_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchBlogByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBlogByNameResponse) ProtoMessage() {}

func (x *SearchBlogByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blogs_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBlogByNameResponse.ProtoReflect.Descriptor instead.
func (*SearchBlogByNameResponse) Descriptor() ([]byte, []int) {
	return file_blogs_service_proto_rawDescGZIP(), []int{15}
}

func (x *SearchBlogByNameResponse) GetBlogs() []*Blog {
	if x != nil {
		return x.Blogs
	}
	return nil
}

type PublishBlogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *PublishBlogRequest) Reset() {
	*x = PublishBlogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blogs_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBlogRequest) ProtoMessage() {}

func (x *PublishBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blogs_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBlogRequest.ProtoReflect.Descriptor instead.
func (*PublishBlogRequest) Descriptor() ([]byte, []int) {
	return file_blogs_service_proto_rawDescGZIP(), []int{16}
}

func (x *PublishBlogRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type PublishBlogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PublishBlogResponse) Reset() {
	*x = PublishBlogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blogs_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishBlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBlogResponse) ProtoMessage() {}

func (x *PublishBlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blogs_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBlogResponse.ProtoReflect.Descriptor instead.
func (*PublishBlogResponse) Descriptor() ([]byte, []int) {
	return file_blogs_service_proto_rawDescGZIP(), []int{17}
}

type DeleteBlogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteBlogRequest) Reset() {
	*x = DeleteBlogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blogs_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlogRequest) ProtoMessage() {}

func (x *DeleteBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blogs_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlogRequest.ProtoReflect.Descriptor instead.
func (*DeleteBlogRequest) Descriptor() ([]byte, []int) {
	return file_blogs_service_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteBlogRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type DeleteBlogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteBlogResponse) Reset() {
	*x = DeleteBlogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blogs_service_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlogResponse) ProtoMessage() {}

func (x *DeleteBlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blogs_service_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlogResponse.ProtoReflect.Descriptor instead.
func (*DeleteBlogResponse) Descriptor() ([]byte, []int) {
	return file_blogs_service_proto_rawDescGZIP(), []int{19}
}

var File_blogs_service_proto protoreflect.FileDescriptor

var file_blogs_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xeb, 0x02, 0x0a, 0x04, 0x42, 0x6c, 0x6f, 0x67, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12,
	0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x2e, 0x42,
	0x6c, 0x6f, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x28, 0x0a,
	0x08, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1f, 0x0a, 0x05, 0x56, 0x6f, 0x74, 0x65, 0x73,
	0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x56, 0x6f, 0x74,
	0x65, 0x52, 0x05, 0x56, 0x6f, 0x74, 0x65, 0x73, 0x12, 0x3e, 0x0a, 0x0f, 0x52, 0x65, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0f, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x4a, 0x0a, 0x0a, 0x42, 0x6c, 0x6f, 0x67,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x09, 0x0a, 0x05, 0x44, 0x72, 0x61, 0x66, 0x74, 0x10,
	0x00, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x10, 0x01,
	0x12, 0x0a, 0x0a, 0x06, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x61, 0x6d, 0x6f,
	0x75, 0x73, 0x10, 0x04, 0x22, 0xba, 0x01, 0x0a, 0x13, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06,
	0x42, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x42, 0x6c,
	0x6f, 0x67, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x52, 0x65, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x3a, 0x0a, 0x18, 0x52, 0x65,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x18, 0x52, 0x65,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x04, 0x62, 0x6c, 0x6f, 0x67, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x04, 0x62, 0x6c, 0x6f,
	0x67, 0x22, 0xd9, 0x01, 0x0a, 0x0b, 0x42, 0x6c, 0x6f, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x42, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x42,
	0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x65, 0x78, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x98, 0x01,
	0x0a, 0x08, 0x42, 0x6c, 0x6f, 0x67, 0x56, 0x6f, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x42, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x56,
	0x6f, 0x74, 0x65, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x22, 0x24, 0x0a, 0x08, 0x56, 0x6f, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c,
	0x0a, 0x08, 0x44, 0x6f, 0x77, 0x6e, 0x76, 0x6f, 0x74, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x55, 0x70, 0x76, 0x6f, 0x74, 0x65, 0x10, 0x01, 0x22, 0x2e, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a,
	0x04, 0x62, 0x6c, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x42, 0x6c,
	0x6f, 0x67, 0x52, 0x04, 0x62, 0x6c, 0x6f, 0x67, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x24,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x44, 0x22, 0x30, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x04, 0x62,
	0x6c, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x42, 0x6c, 0x6f, 0x67,
	0x52, 0x04, 0x62, 0x6c, 0x6f, 0x67, 0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x42, 0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x32, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x05, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x67, 0x73,
	0x22, 0x38, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x42, 0x79, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x73, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x3a, 0x0a, 0x1b, 0x47, 0x65,
	0x74, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x42, 0x79, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x49,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x05, 0x62, 0x6c, 0x6f,
	0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x52,
	0x05, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x22, 0x3d, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f,
	0x67, 0x73, 0x42, 0x79, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x49, 0x64, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73,
	0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x73, 0x49, 0x64, 0x73, 0x22, 0x3b, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67,
	0x73, 0x42, 0x79, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x49, 0x64, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x05, 0x62, 0x6c, 0x6f,
	0x67, 0x73, 0x22, 0x2f, 0x0a, 0x17, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x6c, 0x6f, 0x67,
	0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69,
	0x74, 0x6c, 0x65, 0x22, 0x37, 0x0a, 0x18, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x6c, 0x6f,
	0x67, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1b, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05,
	0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x22, 0x24, 0x0a, 0x12,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x49, 0x44, 0x22, 0x15, 0x0a, 0x13, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x42, 0x6c, 0x6f,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x23, 0x0a, 0x11, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x14,
	0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0xaa, 0x04, 0x0a, 0x0c, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42,
	0x6c, 0x6f, 0x67, 0x12, 0x12, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a,
	0x0a, 0x0b, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x12, 0x13, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x6c, 0x6f, 0x67, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x42, 0x6c, 0x6f, 0x67, 0x42, 0x79, 0x49, 0x64, 0x12, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x42,
	0x6c, 0x6f, 0x67, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14,
	0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f,
	0x67, 0x73, 0x42, 0x79, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x49, 0x64, 0x12, 0x1b, 0x2e,
	0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x42, 0x79, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x73, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x47, 0x65, 0x74,
	0x42, 0x6c, 0x6f, 0x67, 0x73, 0x42, 0x79, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x49, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x42, 0x79, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x49,
	0x64, 0x73, 0x12, 0x1c, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x42, 0x79, 0x41,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x42, 0x79, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x73, 0x49, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x49, 0x0a, 0x10, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x6c, 0x6f, 0x67, 0x42,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x6c,
	0x6f, 0x67, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x6c, 0x6f, 0x67, 0x42, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0b,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x42, 0x6c, 0x6f, 0x67, 0x12, 0x13, 0x2e, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x14, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x12, 0x12, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42,
	0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x6c, 0x6f, 0x67, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_blogs_service_proto_rawDescOnce sync.Once
	file_blogs_service_proto_rawDescData = file_blogs_service_proto_rawDesc
)

func file_blogs_service_proto_rawDescGZIP() []byte {
	file_blogs_service_proto_rawDescOnce.Do(func() {
		file_blogs_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_blogs_service_proto_rawDescData)
	})
	return file_blogs_service_proto_rawDescData
}

var file_blogs_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_blogs_service_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_blogs_service_proto_goTypes = []interface{}{
	(Blog_BlogStatus)(0),                 // 0: Blog.BlogStatus
	(BlogVote_VoteType)(0),               // 1: BlogVote.VoteType
	(*Blog)(nil),                         // 2: Blog
	(*BlogsRecommendation)(nil),          // 3: BlogsRecommendation
	(*BlogComment)(nil),                  // 4: BlogComment
	(*BlogVote)(nil),                     // 5: BlogVote
	(*CreateBlogRequest)(nil),            // 6: CreateBlogRequest
	(*CreateBlogResponse)(nil),           // 7: CreateBlogResponse
	(*GetBlogByIdRequest)(nil),           // 8: GetBlogByIdRequest
	(*GetBlogByIdResponse)(nil),          // 9: GetBlogByIdResponse
	(*GetAllBlogsRequest)(nil),           // 10: GetAllBlogsRequest
	(*GetAllBlogsResponse)(nil),          // 11: GetAllBlogsResponse
	(*GetBlogsByAuthorsIdRequest)(nil),   // 12: GetBlogsByAuthorsIdRequest
	(*GetBlogsByAuthorsIdResponse)(nil),  // 13: GetBlogsByAuthorsIdResponse
	(*GetBlogsByAuthorsIdsRequest)(nil),  // 14: GetBlogsByAuthorsIdsRequest
	(*GetBlogsByAuthorsIdsResponse)(nil), // 15: GetBlogsByAuthorsIdsResponse
	(*SearchBlogByNameRequest)(nil),      // 16: SearchBlogByNameRequest
	(*SearchBlogByNameResponse)(nil),     // 17: SearchBlogByNameResponse
	(*PublishBlogRequest)(nil),           // 18: PublishBlogRequest
	(*PublishBlogResponse)(nil),          // 19: PublishBlogResponse
	(*DeleteBlogRequest)(nil),            // 20: DeleteBlogRequest
	(*DeleteBlogResponse)(nil),           // 21: DeleteBlogResponse
	(*timestamppb.Timestamp)(nil),        // 22: google.protobuf.Timestamp
}
var file_blogs_service_proto_depIdxs = []int32{
	0,  // 0: Blog.Status:type_name -> Blog.BlogStatus
	4,  // 1: Blog.Comments:type_name -> BlogComment
	5,  // 2: Blog.Votes:type_name -> BlogVote
	3,  // 3: Blog.Recommendations:type_name -> BlogsRecommendation
	2,  // 4: BlogsRecommendation.blog:type_name -> Blog
	22, // 5: BlogComment.CreatedAt:type_name -> google.protobuf.Timestamp
	22, // 6: BlogComment.UpdatedAt:type_name -> google.protobuf.Timestamp
	1,  // 7: BlogVote.Type:type_name -> BlogVote.VoteType
	2,  // 8: CreateBlogRequest.blog:type_name -> Blog
	2,  // 9: GetBlogByIdResponse.blog:type_name -> Blog
	2,  // 10: GetAllBlogsResponse.blogs:type_name -> Blog
	2,  // 11: GetBlogsByAuthorsIdResponse.blogs:type_name -> Blog
	2,  // 12: GetBlogsByAuthorsIdsResponse.blogs:type_name -> Blog
	2,  // 13: SearchBlogByNameResponse.blogs:type_name -> Blog
	6,  // 14: BlogsService.CreateBlog:input_type -> CreateBlogRequest
	10, // 15: BlogsService.GetAllBlogs:input_type -> GetAllBlogsRequest
	8,  // 16: BlogsService.GetBlogById:input_type -> GetBlogByIdRequest
	12, // 17: BlogsService.GetBlogsByAuthorsId:input_type -> GetBlogsByAuthorsIdRequest
	14, // 18: BlogsService.GetBlogsByAuthorsIds:input_type -> GetBlogsByAuthorsIdsRequest
	16, // 19: BlogsService.SearchBlogByName:input_type -> SearchBlogByNameRequest
	18, // 20: BlogsService.PublishBlog:input_type -> PublishBlogRequest
	20, // 21: BlogsService.DeleteBlog:input_type -> DeleteBlogRequest
	7,  // 22: BlogsService.CreateBlog:output_type -> CreateBlogResponse
	11, // 23: BlogsService.GetAllBlogs:output_type -> GetAllBlogsResponse
	9,  // 24: BlogsService.GetBlogById:output_type -> GetBlogByIdResponse
	13, // 25: BlogsService.GetBlogsByAuthorsId:output_type -> GetBlogsByAuthorsIdResponse
	15, // 26: BlogsService.GetBlogsByAuthorsIds:output_type -> GetBlogsByAuthorsIdsResponse
	17, // 27: BlogsService.SearchBlogByName:output_type -> SearchBlogByNameResponse
	19, // 28: BlogsService.PublishBlog:output_type -> PublishBlogResponse
	21, // 29: BlogsService.DeleteBlog:output_type -> DeleteBlogResponse
	22, // [22:30] is the sub-list for method output_type
	14, // [14:22] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_blogs_service_proto_init() }
func file_blogs_service_proto_init() {
	if File_blogs_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_blogs_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Blog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blogs_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogsRecommendation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blogs_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogComment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blogs_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogVote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blogs_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBlogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blogs_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBlogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blogs_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlogByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blogs_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlogByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blogs_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllBlogsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blogs_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllBlogsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blogs_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlogsByAuthorsIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blogs_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlogsByAuthorsIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blogs_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlogsByAuthorsIdsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blogs_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlogsByAuthorsIdsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blogs_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchBlogByNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blogs_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchBlogByNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blogs_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishBlogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blogs_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishBlogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blogs_service_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBlogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blogs_service_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBlogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blogs_service_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blogs_service_proto_goTypes,
		DependencyIndexes: file_blogs_service_proto_depIdxs,
		EnumInfos:         file_blogs_service_proto_enumTypes,
		MessageInfos:      file_blogs_service_proto_msgTypes,
	}.Build()
	File_blogs_service_proto = out.File
	file_blogs_service_proto_rawDesc = nil
	file_blogs_service_proto_goTypes = nil
	file_blogs_service_proto_depIdxs = nil
}
