// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.0
// 	protoc        v5.26.1
// source: votes_service.proto

package votes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vote_VoteType int32

const (
	Vote_Downvote Vote_VoteType = 0
	Vote_Upvote   Vote_VoteType = 1
)

// Enum value maps for Vote_VoteType.
var (
	Vote_VoteType_name = map[int32]string{
		0: "Downvote",
		1: "Upvote",
	}
	Vote_VoteType_value = map[string]int32{
		"Downvote": 0,
		"Upvote":   1,
	}
)

func (x Vote_VoteType) Enum() *Vote_VoteType {
	p := new(Vote_VoteType)
	*p = x
	return p
}

func (x Vote_VoteType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Vote_VoteType) Descriptor() protoreflect.EnumDescriptor {
	return file_votes_service_proto_enumTypes[0].Descriptor()
}

func (Vote_VoteType) Type() protoreflect.EnumType {
	return &file_votes_service_proto_enumTypes[0]
}

func (x Vote_VoteType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Vote_VoteType.Descriptor instead.
func (Vote_VoteType) EnumDescriptor() ([]byte, []int) {
	return file_votes_service_proto_rawDescGZIP(), []int{0, 0}
}

type Vote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     int32         `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserId int32         `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	BlogId int32         `protobuf:"varint,3,opt,name=BlogId,proto3" json:"BlogId,omitempty"`
	Type   Vote_VoteType `protobuf:"varint,4,opt,name=Type,proto3,enum=Vote_VoteType" json:"Type,omitempty"`
}

func (x *Vote) Reset() {
	*x = Vote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_votes_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vote) ProtoMessage() {}

func (x *Vote) ProtoReflect() protoreflect.Message {
	mi := &file_votes_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vote.ProtoReflect.Descriptor instead.
func (*Vote) Descriptor() ([]byte, []int) {
	return file_votes_service_proto_rawDescGZIP(), []int{0}
}

func (x *Vote) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Vote) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Vote) GetBlogId() int32 {
	if x != nil {
		return x.BlogId
	}
	return 0
}

func (x *Vote) GetType() Vote_VoteType {
	if x != nil {
		return x.Type
	}
	return Vote_Downvote
}

type GetVoteByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetVoteByIdRequest) Reset() {
	*x = GetVoteByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_votes_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVoteByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVoteByIdRequest) ProtoMessage() {}

func (x *GetVoteByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_votes_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVoteByIdRequest.ProtoReflect.Descriptor instead.
func (*GetVoteByIdRequest) Descriptor() ([]byte, []int) {
	return file_votes_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetVoteByIdRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetVoteByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vote *Vote `protobuf:"bytes,1,opt,name=vote,proto3" json:"vote,omitempty"`
}

func (x *GetVoteByIdResponse) Reset() {
	*x = GetVoteByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_votes_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVoteByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVoteByIdResponse) ProtoMessage() {}

func (x *GetVoteByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_votes_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVoteByIdResponse.ProtoReflect.Descriptor instead.
func (*GetVoteByIdResponse) Descriptor() ([]byte, []int) {
	return file_votes_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetVoteByIdResponse) GetVote() *Vote {
	if x != nil {
		return x.Vote
	}
	return nil
}

type GetAllVotesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllVotesRequest) Reset() {
	*x = GetAllVotesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_votes_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllVotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllVotesRequest) ProtoMessage() {}

func (x *GetAllVotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_votes_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllVotesRequest.ProtoReflect.Descriptor instead.
func (*GetAllVotesRequest) Descriptor() ([]byte, []int) {
	return file_votes_service_proto_rawDescGZIP(), []int{3}
}

type GetAllVotesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Votes []*Vote `protobuf:"bytes,1,rep,name=votes,proto3" json:"votes,omitempty"`
}

func (x *GetAllVotesResponse) Reset() {
	*x = GetAllVotesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_votes_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllVotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllVotesResponse) ProtoMessage() {}

func (x *GetAllVotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_votes_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllVotesResponse.ProtoReflect.Descriptor instead.
func (*GetAllVotesResponse) Descriptor() ([]byte, []int) {
	return file_votes_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllVotesResponse) GetVotes() []*Vote {
	if x != nil {
		return x.Votes
	}
	return nil
}

var File_votes_service_proto protoreflect.FileDescriptor

var file_votes_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x76, 0x6f, 0x74, 0x65, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x90, 0x01, 0x0a, 0x04, 0x56, 0x6f, 0x74, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x16,
	0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x6c, 0x6f, 0x67, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x42, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x22,
	0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x56,
	0x6f, 0x74, 0x65, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x22, 0x24, 0x0a, 0x08, 0x56, 0x6f, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c,
	0x0a, 0x08, 0x44, 0x6f, 0x77, 0x6e, 0x76, 0x6f, 0x74, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x55, 0x70, 0x76, 0x6f, 0x74, 0x65, 0x10, 0x01, 0x22, 0x24, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x56,
	0x6f, 0x74, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x30,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x56, 0x6f, 0x74, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x04, 0x76, 0x6f, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x04, 0x76, 0x6f, 0x74, 0x65,
	0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x56, 0x6f, 0x74, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x32, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x56, 0x6f, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a,
	0x05, 0x76, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x56,
	0x6f, 0x74, 0x65, 0x52, 0x05, 0x76, 0x6f, 0x74, 0x65, 0x73, 0x32, 0x86, 0x01, 0x0a, 0x0c, 0x56,
	0x6f, 0x74, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x0b, 0x47,
	0x65, 0x74, 0x56, 0x6f, 0x74, 0x65, 0x42, 0x79, 0x49, 0x64, 0x12, 0x13, 0x2e, 0x47, 0x65, 0x74,
	0x56, 0x6f, 0x74, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x14, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x6f, 0x74, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x56, 0x6f, 0x74, 0x65, 0x73, 0x12, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x56,
	0x6f, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x56, 0x6f, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x6f, 0x74,
	0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_votes_service_proto_rawDescOnce sync.Once
	file_votes_service_proto_rawDescData = file_votes_service_proto_rawDesc
)

func file_votes_service_proto_rawDescGZIP() []byte {
	file_votes_service_proto_rawDescOnce.Do(func() {
		file_votes_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_votes_service_proto_rawDescData)
	})
	return file_votes_service_proto_rawDescData
}

var file_votes_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_votes_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_votes_service_proto_goTypes = []interface{}{
	(Vote_VoteType)(0),          // 0: Vote.VoteType
	(*Vote)(nil),                // 1: Vote
	(*GetVoteByIdRequest)(nil),  // 2: GetVoteByIdRequest
	(*GetVoteByIdResponse)(nil), // 3: GetVoteByIdResponse
	(*GetAllVotesRequest)(nil),  // 4: GetAllVotesRequest
	(*GetAllVotesResponse)(nil), // 5: GetAllVotesResponse
}
var file_votes_service_proto_depIdxs = []int32{
	0, // 0: Vote.Type:type_name -> Vote.VoteType
	1, // 1: GetVoteByIdResponse.vote:type_name -> Vote
	1, // 2: GetAllVotesResponse.votes:type_name -> Vote
	2, // 3: VotesService.GetVoteById:input_type -> GetVoteByIdRequest
	4, // 4: VotesService.GetAllVotes:input_type -> GetAllVotesRequest
	3, // 5: VotesService.GetVoteById:output_type -> GetVoteByIdResponse
	5, // 6: VotesService.GetAllVotes:output_type -> GetAllVotesResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_votes_service_proto_init() }
func file_votes_service_proto_init() {
	if File_votes_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_votes_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_votes_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVoteByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_votes_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVoteByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_votes_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllVotesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_votes_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllVotesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_votes_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_votes_service_proto_goTypes,
		DependencyIndexes: file_votes_service_proto_depIdxs,
		EnumInfos:         file_votes_service_proto_enumTypes,
		MessageInfos:      file_votes_service_proto_msgTypes,
	}.Build()
	File_votes_service_proto = out.File
	file_votes_service_proto_rawDesc = nil
	file_votes_service_proto_goTypes = nil
	file_votes_service_proto_depIdxs = nil
}
