// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: votes_service.proto

package votes

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	VotesService_GetVoteById_FullMethodName = "/VotesService/GetVoteById"
	VotesService_GetAllVotes_FullMethodName = "/VotesService/GetAllVotes"
)

// VotesServiceClient is the client API for VotesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VotesServiceClient interface {
	GetVoteById(ctx context.Context, in *GetVoteByIdRequest, opts ...grpc.CallOption) (*GetVoteByIdResponse, error)
	GetAllVotes(ctx context.Context, in *GetAllVotesRequest, opts ...grpc.CallOption) (*GetAllVotesResponse, error)
}

type votesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVotesServiceClient(cc grpc.ClientConnInterface) VotesServiceClient {
	return &votesServiceClient{cc}
}

func (c *votesServiceClient) GetVoteById(ctx context.Context, in *GetVoteByIdRequest, opts ...grpc.CallOption) (*GetVoteByIdResponse, error) {
	out := new(GetVoteByIdResponse)
	err := c.cc.Invoke(ctx, VotesService_GetVoteById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *votesServiceClient) GetAllVotes(ctx context.Context, in *GetAllVotesRequest, opts ...grpc.CallOption) (*GetAllVotesResponse, error) {
	out := new(GetAllVotesResponse)
	err := c.cc.Invoke(ctx, VotesService_GetAllVotes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VotesServiceServer is the server API for VotesService service.
// All implementations must embed UnimplementedVotesServiceServer
// for forward compatibility
type VotesServiceServer interface {
	GetVoteById(context.Context, *GetVoteByIdRequest) (*GetVoteByIdResponse, error)
	GetAllVotes(context.Context, *GetAllVotesRequest) (*GetAllVotesResponse, error)
	mustEmbedUnimplementedVotesServiceServer()
}

// UnimplementedVotesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVotesServiceServer struct {
}

func (UnimplementedVotesServiceServer) GetVoteById(context.Context, *GetVoteByIdRequest) (*GetVoteByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVoteById not implemented")
}
func (UnimplementedVotesServiceServer) GetAllVotes(context.Context, *GetAllVotesRequest) (*GetAllVotesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllVotes not implemented")
}
func (UnimplementedVotesServiceServer) mustEmbedUnimplementedVotesServiceServer() {}

// UnsafeVotesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VotesServiceServer will
// result in compilation errors.
type UnsafeVotesServiceServer interface {
	mustEmbedUnimplementedVotesServiceServer()
}

func RegisterVotesServiceServer(s grpc.ServiceRegistrar, srv VotesServiceServer) {
	s.RegisterService(&VotesService_ServiceDesc, srv)
}

func _VotesService_GetVoteById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVoteByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VotesServiceServer).GetVoteById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VotesService_GetVoteById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VotesServiceServer).GetVoteById(ctx, req.(*GetVoteByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VotesService_GetAllVotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllVotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VotesServiceServer).GetAllVotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VotesService_GetAllVotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VotesServiceServer).GetAllVotes(ctx, req.(*GetAllVotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VotesService_ServiceDesc is the grpc.ServiceDesc for VotesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VotesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "VotesService",
	HandlerType: (*VotesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVoteById",
			Handler:    _VotesService_GetVoteById_Handler,
		},
		{
			MethodName: "GetAllVotes",
			Handler:    _VotesService_GetAllVotes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "votes_service.proto",
}
