version: '3.9'

services:

  loki:
    image: grafana/loki:main-5206e3a
    networks:
      - database

  grafana:
    image: grafana/grafana:8.5.3
    ports:
      - "3000:3000"
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - database

  renderer:
    image: grafana/grafana-image-renderer:3.4.2
    environment:
      ENABLE_METRICS: "true"
    networks:
      - database

  jaeger:
    image: jaegertracing/all-in-one:1.34
    ports:
      - "9000:16686"
    networks:
      - database

  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:main-5206e3a-amd64
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - "24224:24224"
      - "24224:24224/tcp"
      - "24224:24224/udp"
    networks:
      - database

volumes:
  grafana:
    name: grafana

networks:
  database:
    name: database
    driver: bridge
