// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: equipment_service.proto

package equipment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	EquipmentService_GetEquipmentById_FullMethodName = "/EquipmentService/GetEquipmentById"
	EquipmentService_GetAllEquipment_FullMethodName  = "/EquipmentService/GetAllEquipment"
	EquipmentService_CreateEquipment_FullMethodName  = "/EquipmentService/CreateEquipment"
)

// EquipmentServiceClient is the client API for EquipmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EquipmentServiceClient interface {
	GetEquipmentById(ctx context.Context, in *GetEquipmentByIdRequest, opts ...grpc.CallOption) (*GetEquipmentByIdResponse, error)
	GetAllEquipment(ctx context.Context, in *GetAllEquipmentRequest, opts ...grpc.CallOption) (*GetAllEquipmentResponse, error)
	CreateEquipment(ctx context.Context, in *CreateEquipmentRequest, opts ...grpc.CallOption) (*CreateEquipmentResponse, error)
}

type equipmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEquipmentServiceClient(cc grpc.ClientConnInterface) EquipmentServiceClient {
	return &equipmentServiceClient{cc}
}

func (c *equipmentServiceClient) GetEquipmentById(ctx context.Context, in *GetEquipmentByIdRequest, opts ...grpc.CallOption) (*GetEquipmentByIdResponse, error) {
	out := new(GetEquipmentByIdResponse)
	err := c.cc.Invoke(ctx, EquipmentService_GetEquipmentById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) GetAllEquipment(ctx context.Context, in *GetAllEquipmentRequest, opts ...grpc.CallOption) (*GetAllEquipmentResponse, error) {
	out := new(GetAllEquipmentResponse)
	err := c.cc.Invoke(ctx, EquipmentService_GetAllEquipment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) CreateEquipment(ctx context.Context, in *CreateEquipmentRequest, opts ...grpc.CallOption) (*CreateEquipmentResponse, error) {
	out := new(CreateEquipmentResponse)
	err := c.cc.Invoke(ctx, EquipmentService_CreateEquipment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EquipmentServiceServer is the server API for EquipmentService service.
// All implementations must embed UnimplementedEquipmentServiceServer
// for forward compatibility
type EquipmentServiceServer interface {
	GetEquipmentById(context.Context, *GetEquipmentByIdRequest) (*GetEquipmentByIdResponse, error)
	GetAllEquipment(context.Context, *GetAllEquipmentRequest) (*GetAllEquipmentResponse, error)
	CreateEquipment(context.Context, *CreateEquipmentRequest) (*CreateEquipmentResponse, error)
	mustEmbedUnimplementedEquipmentServiceServer()
}

// UnimplementedEquipmentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEquipmentServiceServer struct {
}

func (UnimplementedEquipmentServiceServer) GetEquipmentById(context.Context, *GetEquipmentByIdRequest) (*GetEquipmentByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEquipmentById not implemented")
}
func (UnimplementedEquipmentServiceServer) GetAllEquipment(context.Context, *GetAllEquipmentRequest) (*GetAllEquipmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllEquipment not implemented")
}
func (UnimplementedEquipmentServiceServer) CreateEquipment(context.Context, *CreateEquipmentRequest) (*CreateEquipmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEquipment not implemented")
}
func (UnimplementedEquipmentServiceServer) mustEmbedUnimplementedEquipmentServiceServer() {}

// UnsafeEquipmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EquipmentServiceServer will
// result in compilation errors.
type UnsafeEquipmentServiceServer interface {
	mustEmbedUnimplementedEquipmentServiceServer()
}

func RegisterEquipmentServiceServer(s grpc.ServiceRegistrar, srv EquipmentServiceServer) {
	s.RegisterService(&EquipmentService_ServiceDesc, srv)
}

func _EquipmentService_GetEquipmentById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEquipmentByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).GetEquipmentById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EquipmentService_GetEquipmentById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).GetEquipmentById(ctx, req.(*GetEquipmentByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_GetAllEquipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllEquipmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).GetAllEquipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EquipmentService_GetAllEquipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).GetAllEquipment(ctx, req.(*GetAllEquipmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_CreateEquipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEquipmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).CreateEquipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EquipmentService_CreateEquipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).CreateEquipment(ctx, req.(*CreateEquipmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EquipmentService_ServiceDesc is the grpc.ServiceDesc for EquipmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EquipmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "EquipmentService",
	HandlerType: (*EquipmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEquipmentById",
			Handler:    _EquipmentService_GetEquipmentById_Handler,
		},
		{
			MethodName: "GetAllEquipment",
			Handler:    _EquipmentService_GetAllEquipment_Handler,
		},
		{
			MethodName: "CreateEquipment",
			Handler:    _EquipmentService_CreateEquipment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "equipment_service.proto",
}
