// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.0
// 	protoc        v5.26.1
// source: keypoints_service.proto

package keypoints

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID              int64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	TourId          int64   `protobuf:"varint,2,opt,name=TourId,proto3" json:"TourId,omitempty"`
	Name            string  `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Description     string  `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	Longitude       float64 `protobuf:"fixed64,5,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	Latitude        float64 `protobuf:"fixed64,6,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	LocationAddress string  `protobuf:"bytes,7,opt,name=LocationAddress,proto3" json:"LocationAddress,omitempty"`
	ImagePath       string  `protobuf:"bytes,8,opt,name=ImagePath,proto3" json:"ImagePath,omitempty"`
	Order           int64   `protobuf:"varint,9,opt,name=Order,proto3" json:"Order,omitempty"`
}

func (x *KeyPoint) Reset() {
	*x = KeyPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keypoints_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPoint) ProtoMessage() {}

func (x *KeyPoint) ProtoReflect() protoreflect.Message {
	mi := &file_keypoints_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPoint.ProtoReflect.Descriptor instead.
func (*KeyPoint) Descriptor() ([]byte, []int) {
	return file_keypoints_service_proto_rawDescGZIP(), []int{0}
}

func (x *KeyPoint) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *KeyPoint) GetTourId() int64 {
	if x != nil {
		return x.TourId
	}
	return 0
}

func (x *KeyPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KeyPoint) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *KeyPoint) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *KeyPoint) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *KeyPoint) GetLocationAddress() string {
	if x != nil {
		return x.LocationAddress
	}
	return ""
}

func (x *KeyPoint) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

func (x *KeyPoint) GetOrder() int64 {
	if x != nil {
		return x.Order
	}
	return 0
}

type KeyPointGetByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *KeyPointGetByIdRequest) Reset() {
	*x = KeyPointGetByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keypoints_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyPointGetByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPointGetByIdRequest) ProtoMessage() {}

func (x *KeyPointGetByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keypoints_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPointGetByIdRequest.ProtoReflect.Descriptor instead.
func (*KeyPointGetByIdRequest) Descriptor() ([]byte, []int) {
	return file_keypoints_service_proto_rawDescGZIP(), []int{1}
}

func (x *KeyPointGetByIdRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type KeyPointGetByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyPoint *KeyPoint `protobuf:"bytes,1,opt,name=keyPoint,proto3" json:"keyPoint,omitempty"`
}

func (x *KeyPointGetByIdResponse) Reset() {
	*x = KeyPointGetByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keypoints_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyPointGetByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPointGetByIdResponse) ProtoMessage() {}

func (x *KeyPointGetByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keypoints_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPointGetByIdResponse.ProtoReflect.Descriptor instead.
func (*KeyPointGetByIdResponse) Descriptor() ([]byte, []int) {
	return file_keypoints_service_proto_rawDescGZIP(), []int{2}
}

func (x *KeyPointGetByIdResponse) GetKeyPoint() *KeyPoint {
	if x != nil {
		return x.KeyPoint
	}
	return nil
}

type KeyPointGetAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KeyPointGetAllRequest) Reset() {
	*x = KeyPointGetAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keypoints_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyPointGetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPointGetAllRequest) ProtoMessage() {}

func (x *KeyPointGetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keypoints_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPointGetAllRequest.ProtoReflect.Descriptor instead.
func (*KeyPointGetAllRequest) Descriptor() ([]byte, []int) {
	return file_keypoints_service_proto_rawDescGZIP(), []int{3}
}

type KeyPointGetAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyPoints []*KeyPoint `protobuf:"bytes,1,rep,name=keyPoints,proto3" json:"keyPoints,omitempty"`
}

func (x *KeyPointGetAllResponse) Reset() {
	*x = KeyPointGetAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keypoints_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyPointGetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPointGetAllResponse) ProtoMessage() {}

func (x *KeyPointGetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keypoints_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPointGetAllResponse.ProtoReflect.Descriptor instead.
func (*KeyPointGetAllResponse) Descriptor() ([]byte, []int) {
	return file_keypoints_service_proto_rawDescGZIP(), []int{4}
}

func (x *KeyPointGetAllResponse) GetKeyPoints() []*KeyPoint {
	if x != nil {
		return x.KeyPoints
	}
	return nil
}

type KeyPointGetByTourIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TourId string `protobuf:"bytes,1,opt,name=TourId,proto3" json:"TourId,omitempty"`
}

func (x *KeyPointGetByTourIdRequest) Reset() {
	*x = KeyPointGetByTourIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keypoints_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyPointGetByTourIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPointGetByTourIdRequest) ProtoMessage() {}

func (x *KeyPointGetByTourIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keypoints_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPointGetByTourIdRequest.ProtoReflect.Descriptor instead.
func (*KeyPointGetByTourIdRequest) Descriptor() ([]byte, []int) {
	return file_keypoints_service_proto_rawDescGZIP(), []int{5}
}

func (x *KeyPointGetByTourIdRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

type KeyPointGetByTourIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyPoints []*KeyPoint `protobuf:"bytes,1,rep,name=keyPoints,proto3" json:"keyPoints,omitempty"`
}

func (x *KeyPointGetByTourIdResponse) Reset() {
	*x = KeyPointGetByTourIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keypoints_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyPointGetByTourIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPointGetByTourIdResponse) ProtoMessage() {}

func (x *KeyPointGetByTourIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keypoints_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPointGetByTourIdResponse.ProtoReflect.Descriptor instead.
func (*KeyPointGetByTourIdResponse) Descriptor() ([]byte, []int) {
	return file_keypoints_service_proto_rawDescGZIP(), []int{6}
}

func (x *KeyPointGetByTourIdResponse) GetKeyPoints() []*KeyPoint {
	if x != nil {
		return x.KeyPoints
	}
	return nil
}

type KeyPointCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyPoint *KeyPoint `protobuf:"bytes,1,opt,name=keyPoint,proto3" json:"keyPoint,omitempty"`
}

func (x *KeyPointCreateRequest) Reset() {
	*x = KeyPointCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keypoints_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyPointCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPointCreateRequest) ProtoMessage() {}

func (x *KeyPointCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keypoints_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPointCreateRequest.ProtoReflect.Descriptor instead.
func (*KeyPointCreateRequest) Descriptor() ([]byte, []int) {
	return file_keypoints_service_proto_rawDescGZIP(), []int{7}
}

func (x *KeyPointCreateRequest) GetKeyPoint() *KeyPoint {
	if x != nil {
		return x.KeyPoint
	}
	return nil
}

type KeyPointCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KeyPointCreateResponse) Reset() {
	*x = KeyPointCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keypoints_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyPointCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPointCreateResponse) ProtoMessage() {}

func (x *KeyPointCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keypoints_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPointCreateResponse.ProtoReflect.Descriptor instead.
func (*KeyPointCreateResponse) Descriptor() ([]byte, []int) {
	return file_keypoints_service_proto_rawDescGZIP(), []int{8}
}

type KeyPointUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyPoint *KeyPoint `protobuf:"bytes,1,opt,name=keyPoint,proto3" json:"keyPoint,omitempty"`
}

func (x *KeyPointUpdateRequest) Reset() {
	*x = KeyPointUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keypoints_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyPointUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPointUpdateRequest) ProtoMessage() {}

func (x *KeyPointUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keypoints_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPointUpdateRequest.ProtoReflect.Descriptor instead.
func (*KeyPointUpdateRequest) Descriptor() ([]byte, []int) {
	return file_keypoints_service_proto_rawDescGZIP(), []int{9}
}

func (x *KeyPointUpdateRequest) GetKeyPoint() *KeyPoint {
	if x != nil {
		return x.KeyPoint
	}
	return nil
}

type KeyPointUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KeyPointUpdateResponse) Reset() {
	*x = KeyPointUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keypoints_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyPointUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPointUpdateResponse) ProtoMessage() {}

func (x *KeyPointUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keypoints_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPointUpdateResponse.ProtoReflect.Descriptor instead.
func (*KeyPointUpdateResponse) Descriptor() ([]byte, []int) {
	return file_keypoints_service_proto_rawDescGZIP(), []int{10}
}

type KeyPointDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *KeyPointDeleteRequest) Reset() {
	*x = KeyPointDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keypoints_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyPointDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPointDeleteRequest) ProtoMessage() {}

func (x *KeyPointDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keypoints_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPointDeleteRequest.ProtoReflect.Descriptor instead.
func (*KeyPointDeleteRequest) Descriptor() ([]byte, []int) {
	return file_keypoints_service_proto_rawDescGZIP(), []int{11}
}

func (x *KeyPointDeleteRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type KeyPointDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KeyPointDeleteResponse) Reset() {
	*x = KeyPointDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keypoints_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyPointDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPointDeleteResponse) ProtoMessage() {}

func (x *KeyPointDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keypoints_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPointDeleteResponse.ProtoReflect.Descriptor instead.
func (*KeyPointDeleteResponse) Descriptor() ([]byte, []int) {
	return file_keypoints_service_proto_rawDescGZIP(), []int{12}
}

var File_keypoints_service_proto protoreflect.FileDescriptor

var file_keypoints_service_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6b, 0x65, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x80, 0x02, 0x0a, 0x08, 0x4b, 0x65,
	0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x6f, 0x75, 0x72, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x54, 0x6f, 0x75, 0x72, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x28,
	0x0a, 0x0f, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x28, 0x0a, 0x16,
	0x4b, 0x65, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x40, 0x0a, 0x17, 0x4b, 0x65, 0x79, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x25, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4b, 0x65, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x08,
	0x6b, 0x65, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x4b, 0x65, 0x79, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x41, 0x0a, 0x16, 0x4b, 0x65, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x09, 0x6b,
	0x65, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x4b, 0x65, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x09, 0x6b, 0x65, 0x79, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x73, 0x22, 0x34, 0x0a, 0x1a, 0x4b, 0x65, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x47, 0x65, 0x74, 0x42, 0x79, 0x54, 0x6f, 0x75, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x6f, 0x75, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x54, 0x6f, 0x75, 0x72, 0x49, 0x64, 0x22, 0x46, 0x0a, 0x1b, 0x4b, 0x65,
	0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x42, 0x79, 0x54, 0x6f, 0x75, 0x72, 0x49,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x09, 0x6b, 0x65, 0x79,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4b,
	0x65, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x09, 0x6b, 0x65, 0x79, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x73, 0x22, 0x3e, 0x0a, 0x15, 0x4b, 0x65, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x08, 0x6b,
	0x65, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x4b, 0x65, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x4b, 0x65, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3e, 0x0a, 0x15,
	0x4b, 0x65, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4b, 0x65, 0x79, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0x18, 0x0a, 0x16,
	0x4b, 0x65, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x27, 0x0a, 0x15, 0x4b, 0x65, 0x79, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22,
	0x18, 0x0a, 0x16, 0x4b, 0x65, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x92, 0x03, 0x0a, 0x10, 0x4b, 0x65,
	0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e,
	0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x17, 0x2e, 0x4b, 0x65, 0x79, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x4b, 0x65, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x47, 0x65, 0x74,
	0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b,
	0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x16, 0x2e, 0x4b, 0x65, 0x79, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x17, 0x2e, 0x4b, 0x65, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0b, 0x47,
	0x65, 0x74, 0x42, 0x79, 0x54, 0x6f, 0x75, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x2e, 0x4b, 0x65, 0x79,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x42, 0x79, 0x54, 0x6f, 0x75, 0x72, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x4b, 0x65, 0x79, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x47, 0x65, 0x74, 0x42, 0x79, 0x54, 0x6f, 0x75, 0x72, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x12, 0x16, 0x2e, 0x4b, 0x65, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x4b, 0x65, 0x79, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x16,
	0x2e, 0x4b, 0x65, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x4b, 0x65, 0x79, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x3b, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x4b, 0x65,
	0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x4b, 0x65, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x11,
	0x5a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6b, 0x65, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_keypoints_service_proto_rawDescOnce sync.Once
	file_keypoints_service_proto_rawDescData = file_keypoints_service_proto_rawDesc
)

func file_keypoints_service_proto_rawDescGZIP() []byte {
	file_keypoints_service_proto_rawDescOnce.Do(func() {
		file_keypoints_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_keypoints_service_proto_rawDescData)
	})
	return file_keypoints_service_proto_rawDescData
}

var file_keypoints_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_keypoints_service_proto_goTypes = []interface{}{
	(*KeyPoint)(nil),                    // 0: KeyPoint
	(*KeyPointGetByIdRequest)(nil),      // 1: KeyPointGetByIdRequest
	(*KeyPointGetByIdResponse)(nil),     // 2: KeyPointGetByIdResponse
	(*KeyPointGetAllRequest)(nil),       // 3: KeyPointGetAllRequest
	(*KeyPointGetAllResponse)(nil),      // 4: KeyPointGetAllResponse
	(*KeyPointGetByTourIdRequest)(nil),  // 5: KeyPointGetByTourIdRequest
	(*KeyPointGetByTourIdResponse)(nil), // 6: KeyPointGetByTourIdResponse
	(*KeyPointCreateRequest)(nil),       // 7: KeyPointCreateRequest
	(*KeyPointCreateResponse)(nil),      // 8: KeyPointCreateResponse
	(*KeyPointUpdateRequest)(nil),       // 9: KeyPointUpdateRequest
	(*KeyPointUpdateResponse)(nil),      // 10: KeyPointUpdateResponse
	(*KeyPointDeleteRequest)(nil),       // 11: KeyPointDeleteRequest
	(*KeyPointDeleteResponse)(nil),      // 12: KeyPointDeleteResponse
}
var file_keypoints_service_proto_depIdxs = []int32{
	0,  // 0: KeyPointGetByIdResponse.keyPoint:type_name -> KeyPoint
	0,  // 1: KeyPointGetAllResponse.keyPoints:type_name -> KeyPoint
	0,  // 2: KeyPointGetByTourIdResponse.keyPoints:type_name -> KeyPoint
	0,  // 3: KeyPointCreateRequest.keyPoint:type_name -> KeyPoint
	0,  // 4: KeyPointUpdateRequest.keyPoint:type_name -> KeyPoint
	1,  // 5: KeyPointsService.GetById:input_type -> KeyPointGetByIdRequest
	3,  // 6: KeyPointsService.GetAll:input_type -> KeyPointGetAllRequest
	5,  // 7: KeyPointsService.GetByTourId:input_type -> KeyPointGetByTourIdRequest
	7,  // 8: KeyPointsService.Create:input_type -> KeyPointCreateRequest
	9,  // 9: KeyPointsService.Update:input_type -> KeyPointUpdateRequest
	11, // 10: KeyPointsService.Delete:input_type -> KeyPointDeleteRequest
	2,  // 11: KeyPointsService.GetById:output_type -> KeyPointGetByIdResponse
	4,  // 12: KeyPointsService.GetAll:output_type -> KeyPointGetAllResponse
	6,  // 13: KeyPointsService.GetByTourId:output_type -> KeyPointGetByTourIdResponse
	8,  // 14: KeyPointsService.Create:output_type -> KeyPointCreateResponse
	10, // 15: KeyPointsService.Update:output_type -> KeyPointUpdateResponse
	12, // 16: KeyPointsService.Delete:output_type -> KeyPointDeleteResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_keypoints_service_proto_init() }
func file_keypoints_service_proto_init() {
	if File_keypoints_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_keypoints_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keypoints_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyPointGetByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keypoints_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyPointGetByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keypoints_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyPointGetAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keypoints_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyPointGetAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keypoints_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyPointGetByTourIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keypoints_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyPointGetByTourIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keypoints_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyPointCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keypoints_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyPointCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keypoints_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyPointUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keypoints_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyPointUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keypoints_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyPointDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keypoints_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyPointDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_keypoints_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_keypoints_service_proto_goTypes,
		DependencyIndexes: file_keypoints_service_proto_depIdxs,
		MessageInfos:      file_keypoints_service_proto_msgTypes,
	}.Build()
	File_keypoints_service_proto = out.File
	file_keypoints_service_proto_rawDesc = nil
	file_keypoints_service_proto_goTypes = nil
	file_keypoints_service_proto_depIdxs = nil
}
