version: '3.8'

services:
  
  toursdb:
    image: postgres
    container_name: tours-database
    ports:
      - 5433:5432 # na pgAdmin-u se moze povezati na bazu na port 5433
    environment:
      - POSTGRES_DB=soa-gorm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=super
  
  blogsdb:
    image: postgres
    container_name: blogs-database
    ports:
      - 5434:5432 # na pgAdmin-u se moze povezati na bazu na port 5434
    environment:
      - POSTGRES_DB=soa-blogs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=super

  tours:
    build: tours/ # sam ce build-ovati prvi put, svaki drugi put ce koristiti postojecu sliku koju je build-ovao
    # image: tours # ako vec postoji build-ovana slika (image), komanda za build: go build -t tours tours/
    ports:
      - 8081:8081
    depends_on:
      - toursdb # pre pokretanja ovog kontejnera treba prvo da se pokrene baza

  blogs:
    build: blogs/ # sam ce build-ovati prvi put, svaki drugi put ce koristiti postojecu sliku koju je build-ovao
    # image: blogs # ako vec postoji build-ovana slika (image), komanda za build: go build -t blogs blogs/
    ports:
      - 8082:8082
    depends_on:
      - blogsdb # pre pokretanja ovog kontejnera treba prvo da se pokrene baza

# Slike koje postoje se mogu izlistati komandom: docker images
# Build-ovane slike se mogu izbrisati komandom: docker rmi <slika> (npr. docker rmi tours)
# Slike sa tagom <none> se mogu izbrisati komandom: docker rmi $(docker images --fiter "dangling=true" -q --no-trunc)